# _config.yml
title: Althen Lim's workspace
email: althenlim@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  AI ask me to write my awesone description here. Oh well.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://althenlimzixuan.github.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
